// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.12.4
// source: v1/metrics.proto

package metricsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MetricKind int32

const (
	MetricKind_METRIC_KIND_UNSPECIFIED MetricKind = 0
	MetricKind_GAUGE                   MetricKind = 1
	MetricKind_COUNTER                 MetricKind = 2
)

// Enum value maps for MetricKind.
var (
	MetricKind_name = map[int32]string{
		0: "METRIC_KIND_UNSPECIFIED",
		1: "GAUGE",
		2: "COUNTER",
	}
	MetricKind_value = map[string]int32{
		"METRIC_KIND_UNSPECIFIED": 0,
		"GAUGE":                   1,
		"COUNTER":                 2,
	}
)

func (x MetricKind) Enum() *MetricKind {
	p := new(MetricKind)
	*p = x
	return p
}

func (x MetricKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MetricKind) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_metrics_proto_enumTypes[0].Descriptor()
}

func (MetricKind) Type() protoreflect.EnumType {
	return &file_v1_metrics_proto_enumTypes[0]
}

func (x MetricKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MetricKind.Descriptor instead.
func (MetricKind) EnumDescriptor() ([]byte, []int) {
	return file_v1_metrics_proto_rawDescGZIP(), []int{0}
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_v1_metrics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_v1_metrics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_v1_metrics_proto_rawDescGZIP(), []int{0}
}

type Metric struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                 // имя метрики
	Kind  MetricKind             `protobuf:"varint,2,opt,name=kind,proto3,enum=metrics.v1.MetricKind" json:"kind,omitempty"` // тип
	// Types that are valid to be assigned to Value:
	//
	//	*Metric_Gauge
	//	*Metric_Counter
	Value         isMetric_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metric) Reset() {
	*x = Metric{}
	mi := &file_v1_metrics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metric) ProtoMessage() {}

func (x *Metric) ProtoReflect() protoreflect.Message {
	mi := &file_v1_metrics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metric.ProtoReflect.Descriptor instead.
func (*Metric) Descriptor() ([]byte, []int) {
	return file_v1_metrics_proto_rawDescGZIP(), []int{1}
}

func (x *Metric) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Metric) GetKind() MetricKind {
	if x != nil {
		return x.Kind
	}
	return MetricKind_METRIC_KIND_UNSPECIFIED
}

func (x *Metric) GetValue() isMetric_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Metric) GetGauge() float64 {
	if x != nil {
		if x, ok := x.Value.(*Metric_Gauge); ok {
			return x.Gauge
		}
	}
	return 0
}

func (x *Metric) GetCounter() int64 {
	if x != nil {
		if x, ok := x.Value.(*Metric_Counter); ok {
			return x.Counter
		}
	}
	return 0
}

type isMetric_Value interface {
	isMetric_Value()
}

type Metric_Gauge struct {
	Gauge float64 `protobuf:"fixed64,3,opt,name=gauge,proto3,oneof"` // для GAUGE
}

type Metric_Counter struct {
	Counter int64 `protobuf:"varint,4,opt,name=counter,proto3,oneof"` // для COUNTER (дельта/сумма — как в твоей логике)
}

func (*Metric_Gauge) isMetric_Value() {}

func (*Metric_Counter) isMetric_Value() {}

type MetricsBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Metric              `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsBatch) Reset() {
	*x = MetricsBatch{}
	mi := &file_v1_metrics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsBatch) ProtoMessage() {}

func (x *MetricsBatch) ProtoReflect() protoreflect.Message {
	mi := &file_v1_metrics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsBatch.ProtoReflect.Descriptor instead.
func (*MetricsBatch) Descriptor() ([]byte, []int) {
	return file_v1_metrics_proto_rawDescGZIP(), []int{2}
}

func (x *MetricsBatch) GetItems() []*Metric {
	if x != nil {
		return x.Items
	}
	return nil
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Kind          MetricKind             `protobuf:"varint,2,opt,name=kind,proto3,enum=metrics.v1.MetricKind" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_v1_metrics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_metrics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_v1_metrics_proto_rawDescGZIP(), []int{3}
}

func (x *GetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetRequest) GetKind() MetricKind {
	if x != nil {
		return x.Kind
	}
	return MetricKind_METRIC_KIND_UNSPECIFIED
}

var File_v1_metrics_proto protoreflect.FileDescriptor

const file_v1_metrics_proto_rawDesc = "" +
	"\n" +
	"\x10v1/metrics.proto\x12\n" +
	"metrics.v1\"\a\n" +
	"\x05Empty\"\x81\x01\n" +
	"\x06Metric\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12*\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x16.metrics.v1.MetricKindR\x04kind\x12\x16\n" +
	"\x05gauge\x18\x03 \x01(\x01H\x00R\x05gauge\x12\x1a\n" +
	"\acounter\x18\x04 \x01(\x03H\x00R\acounterB\a\n" +
	"\x05value\"8\n" +
	"\fMetricsBatch\x12(\n" +
	"\x05items\x18\x01 \x03(\v2\x12.metrics.v1.MetricR\x05items\"H\n" +
	"\n" +
	"GetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12*\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x16.metrics.v1.MetricKindR\x04kind*A\n" +
	"\n" +
	"MetricKind\x12\x1b\n" +
	"\x17METRIC_KIND_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05GAUGE\x10\x01\x12\v\n" +
	"\aCOUNTER\x10\x022\xa1\x02\n" +
	"\x0eMetricsService\x12,\n" +
	"\x04Ping\x12\x11.metrics.v1.Empty\x1a\x11.metrics.v1.Empty\x125\n" +
	"\fUpdateMetric\x12\x12.metrics.v1.Metric\x1a\x11.metrics.v1.Empty\x12:\n" +
	"\vUpdateBatch\x12\x18.metrics.v1.MetricsBatch\x1a\x11.metrics.v1.Empty\x127\n" +
	"\tGetMetric\x12\x16.metrics.v1.GetRequest\x1a\x12.metrics.v1.Metric\x125\n" +
	"\x06GetAll\x12\x11.metrics.v1.Empty\x1a\x18.metrics.v1.MetricsBatchBHZFgithub.com/and161185/metrics-alerting/internal/api/metricsv1;metricsv1b\x06proto3"

var (
	file_v1_metrics_proto_rawDescOnce sync.Once
	file_v1_metrics_proto_rawDescData []byte
)

func file_v1_metrics_proto_rawDescGZIP() []byte {
	file_v1_metrics_proto_rawDescOnce.Do(func() {
		file_v1_metrics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_metrics_proto_rawDesc), len(file_v1_metrics_proto_rawDesc)))
	})
	return file_v1_metrics_proto_rawDescData
}

var file_v1_metrics_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_metrics_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_v1_metrics_proto_goTypes = []any{
	(MetricKind)(0),      // 0: metrics.v1.MetricKind
	(*Empty)(nil),        // 1: metrics.v1.Empty
	(*Metric)(nil),       // 2: metrics.v1.Metric
	(*MetricsBatch)(nil), // 3: metrics.v1.MetricsBatch
	(*GetRequest)(nil),   // 4: metrics.v1.GetRequest
}
var file_v1_metrics_proto_depIdxs = []int32{
	0, // 0: metrics.v1.Metric.kind:type_name -> metrics.v1.MetricKind
	2, // 1: metrics.v1.MetricsBatch.items:type_name -> metrics.v1.Metric
	0, // 2: metrics.v1.GetRequest.kind:type_name -> metrics.v1.MetricKind
	1, // 3: metrics.v1.MetricsService.Ping:input_type -> metrics.v1.Empty
	2, // 4: metrics.v1.MetricsService.UpdateMetric:input_type -> metrics.v1.Metric
	3, // 5: metrics.v1.MetricsService.UpdateBatch:input_type -> metrics.v1.MetricsBatch
	4, // 6: metrics.v1.MetricsService.GetMetric:input_type -> metrics.v1.GetRequest
	1, // 7: metrics.v1.MetricsService.GetAll:input_type -> metrics.v1.Empty
	1, // 8: metrics.v1.MetricsService.Ping:output_type -> metrics.v1.Empty
	1, // 9: metrics.v1.MetricsService.UpdateMetric:output_type -> metrics.v1.Empty
	1, // 10: metrics.v1.MetricsService.UpdateBatch:output_type -> metrics.v1.Empty
	2, // 11: metrics.v1.MetricsService.GetMetric:output_type -> metrics.v1.Metric
	3, // 12: metrics.v1.MetricsService.GetAll:output_type -> metrics.v1.MetricsBatch
	8, // [8:13] is the sub-list for method output_type
	3, // [3:8] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_v1_metrics_proto_init() }
func file_v1_metrics_proto_init() {
	if File_v1_metrics_proto != nil {
		return
	}
	file_v1_metrics_proto_msgTypes[1].OneofWrappers = []any{
		(*Metric_Gauge)(nil),
		(*Metric_Counter)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_metrics_proto_rawDesc), len(file_v1_metrics_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_metrics_proto_goTypes,
		DependencyIndexes: file_v1_metrics_proto_depIdxs,
		EnumInfos:         file_v1_metrics_proto_enumTypes,
		MessageInfos:      file_v1_metrics_proto_msgTypes,
	}.Build()
	File_v1_metrics_proto = out.File
	file_v1_metrics_proto_goTypes = nil
	file_v1_metrics_proto_depIdxs = nil
}
