package noosexit

import (
	"go/ast"
	"go/token"
	"testing"

	"golang.org/x/tools/go/analysis"
)

func Test_isGenerated_and_importsTesting(t *testing.T) {
	gen := &ast.File{
		Comments: []*ast.CommentGroup{
			{List: []*ast.Comment{{Text: "// Code generated by tool; DO NOT EDIT."}}},
		},
	}
	if !isGenerated(gen) {
		t.Fatal("isGenerated: want true")
	}

	normal := &ast.File{
		Comments: []*ast.CommentGroup{
			{List: []*ast.Comment{{Text: "// normal file"}}},
		},
	}
	if isGenerated(normal) {
		t.Fatal("isGenerated: want false")
	}

	f := &ast.File{
		Name: ast.NewIdent("p"),
		Imports: []*ast.ImportSpec{
			{Path: &ast.BasicLit{Kind: token.STRING, Value: `"fmt"`}},
			{Path: &ast.BasicLit{Kind: token.STRING, Value: `"testing"`}},
		},
	}
	if !importsTesting(f) {
		t.Fatal("importsTesting: want true")
	}
}

func Test_run_no_violations(t *testing.T) {
	pass := &analysis.Pass{
		Files: []*ast.File{
			{
				Name: ast.NewIdent("main"),
				Decls: []ast.Decl{
					&ast.FuncDecl{
						Name: ast.NewIdent("main"),
						Type: &ast.FuncType{Params: &ast.FieldList{}},
						Body: &ast.BlockStmt{List: []ast.Stmt{
							&ast.ExprStmt{X: ast.NewIdent("println")},
						}},
					},
				},
			},
		},
	}
	if _, err := run(pass); err != nil {
		t.Fatalf("run: %v", err)
	}
}
